find_package(mcop REQUIRED)
find_package(libartsdsp_st REQUIRED)
find_package(libartsc REQUIRED)
find_package(libartsdsp REQUIRED)
find_package(libartscbackend REQUIRED)
find_package(libartsflow REQUIRED)
find_package(libartskde REQUIRED)
find_package(libmcop REQUIRED)
find_package(libmcop_mt REQUIRED)
find_package(libqtmcop REQUIRED)
find_package(libkmedia2 REQUIRED)
find_package(libsoundserver REQUIRED)
find_package(libartswavplayobject REQUIRED)
find_package(libx11globalcomm REQUIRED)

